{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "klustair.serviceAccountName" . }}
  labels:
{{ include "klustair.labels" . | indent 4 }}
---
{{- end -}}
{{- if and .Values.klustairJob.enabled .Values.klustairJob.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "klustair.jobServiceAccountName" . }}
  {{- with .Values.klustairJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
